
services:
  vigs_tool:
    ports:
      - 8088:8088
    volumes:
      - type: bind
        source: $HOME/vigs_sequence_files
        target: /home/vigs_sequence_files
      - type: bind
        source: /home/production/nicotianabase/vigs_mason/header.mas
        target: /home/VIGS/mason/vigs_web/header.mas
    container_name: vigs_tool
    image: breedbase/vigs_tool:v0.01
